<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webTable</name>
   <tag></tag>
   <elementGuidId>704ed67e-67cf-4cce-b10d-1ea6b946af21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/caption[contains(text(),'Delivery')]/following-sibling::tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
