<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DatePicker Enabled_datepicker2</name>
   <tag></tag>
   <elementGuidId>a23fcccc-2f5a-4f55-bcbc-232f9f5b0069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepicker2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datepicker2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0984816-1abd-4f0e-9727-bc9152016777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a42a284c-1899-48bb-a85a-b56813a6e4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker2</value>
      <webElementGuid>2dcd8c01-5556-4187-9a04-47b2b302b9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-datepick</value>
      <webElementGuid>8fa3260c-3731-474a-81be-c1c6d5f8f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker2&quot;)</value>
      <webElementGuid>c15e3b4d-4223-452f-8471-417347061124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepicker2']</value>
      <webElementGuid>6f1b3ee5-f724-434c-95b5-67cdbf558f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>fe462e3e-daef-4e4e-9228-3135b0fecf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datepicker2']</value>
      <webElementGuid>d806aa96-1c8e-4708-b796-78d6b2fdff55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
